services:
  - type: web
    name: postly-app
    env: python
    buildCommand: |
      mkdir -p templates uploads
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    staticPublishPath: ./templates # Ensure templates directory is included
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postly-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: FB_REDIRECT_URI
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        value: noreply@postly.app
      - key: UPLOAD_FOLDER
        value: /tmp/uploads  # Use /tmp for file uploads on Render
      - key: TZ
        value: Asia/Ho_Chi_Minh  # Set timezone for the application

databases:
  - name: postly-db
    plan: free
